---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "unicorn-plex.fullname" . }}-pms-allow-egress
  labels:
    {{- include "unicorn-plex.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "unicorn-plex.loadbalancerSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - {}
